2020-03-23 19:19:29,415 ERROR: Exception on /explore [GET] [in /Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/harry/microblog/app/routes.py", line 129, in explore
    page, app.config['POSTS_PER_PAGE'], False)
  File "/Users/harry/microblog/venv/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 484, in paginate
    if page < 1:
TypeError: '<' not supported between instances of 'str' and 'int'
2020-03-23 19:20:01,186 INFO: Microblog startup [in /Users/harry/microblog/app/__init__.py:41]
2020-03-23 19:41:11,913 INFO: Microblog startup [in /Users/harry/microblog/app/__init__.py:41]
2020-03-23 19:42:59,399 INFO: Microblog startup [in /Users/harry/microblog/app/__init__.py:41]
2020-03-23 19:58:16,726 INFO: Microblog startup [in /Users/harry/microblog/app/__init__.py:41]
